language: ruby
bundler_args: --without development
script:
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rspec
notifications:
  email:
    - webmaster@allospos.io

